name: My Own workflow
on: [push]
jobs:
  Some-Arbitrary-Name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      
  
