name: My Second Workflow master only
on:
  push:
    branches: [ master ]
jobs:
  First-Job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Second Step
        run: |
          ls ${{ github.workspace }}
  Second-Job:
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        run: echo "hello"
